import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GetStaticProps } from "next";
import Link from "../models/Link";
import { useState } from "react";

import prisma from "../lib/prisma";

export const getStaticProps: GetStaticProps = async () => {
  const links = await prisma.link.findMany({
    where: { published: true },
    include: {
      author: {
        select: { email: true },
      },
    },
  });
  return { props: { links } };
};

export interface HomeProps {
  links: Link[];
}

const Home = ({ links }) => {
  const submitData = async (e: React.SyntheticEvent) => {
    e.preventDefault();
    try {
      const body = { username };
      await fetch("/api/updateUser", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
    } catch (error) {
      console.error(error);
    }
  };
  const [username, setUsername] = useState("");
  console.log(links);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <a href="https://stackoverflow.com/questions/63324839/why-using-a-tag-in-nextjs-link">
        Hello
      </a>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <form onSubmit={(e) => submitData(e)}>
            <h1>Username</h1>
            <input
              autoFocus
              onChange={(e) => setUsername(e.target.value)}
              placeholder="username"
              type="text"
              value={username}
            />

            <input disabled={!username} type="submit" value="Create" />
          </form>

          {links.map((link) => {
            return <div key={link.id}>{link.userId}</div>;
          })}

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <p>Discover and deploy boilerplate example Next.js projects.</p>
            <h2>Examples &rarr;</h2>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
